INSERT INTO CAR(CAR_BRAND, CAR_MODEL, CAR_COUPE, CAR_DESCRIPTION,
                CAR_PRICE_PER_DAY, CAR_FUEL, CAR_TRANSMISSION, CAR_YEAR) VALUES
('Toyota', 'Yaris', 'Hatchback', 'Up to 2019, Toyota had used the Yaris nameplate on export versions of various Japanese-market models, with some markets receiving the same vehicles under the Toyota Echo name through 2005. Starting in 2020, the Yaris nameplate began to be used in Japan, which replaced the Vitz nameplate.', 70, 'petrol', 'Manual', 2018),
('Audi', 'A6', 'Sedan', 'The 2019 Audi A6 comes in three trims: Premium, Premium Plus, and Prestige. The Premium and Premium Plus trims feature a 248-horsepower turbocharged four-cylinder engine and are available with a 335-horsepower turbocharged V6. ... When new, Audi offered a lot of options for the 2019 A6.', 150, 'Diesel', 'Automatic', 2019),
('Ford', 'F150', 'Truck', 'Despite being a big truck, this Ford delivers a smooth ride, even over rough pavement. It also remains composed on twisty roads. Available engines: 2.7-liter twin-turbocharged V6 with 325 horsepower and 400 pound-feet of torque (available in XL, XLT; standard in Lariat)', 300, 'petrol', 'Automatic', 2016),
('Chevrolet', 'Captiva', 'Jeep', 'The Chevrolet Captiva is a compact crossover SUV developed by General Motors. The first generation was developed by GM Korea, based on the GM Theta platform and derived from the S3X concept car revealed in 2004. The crossover straddles the entry-level SUV segments.', 170, 'diesel', 'Automatic', 2018),
('Opel', 'Adam', 'Jeep', 'The Opel Adam was a city car engineered and produced by the German car manufacturer Opel, and is named after the company\'s founder Adam Opel.', 200, 'diesel', 'Manual', 2019),
('Citroen', 'Cactus', 'Jeet', 'The Citroën C4 Cactus is a subcompact crossover SUV, produced by French automaker Citroën in Spain between April 2014 and December 2017, with production of the second generation commencing in October 2017 (until May 2020 in Villaverde), with the final months of production being disrupted by the COVID-19 pandemic. The C4 Cactus is considered a compact SUV, although it is based on the PSA PF1 platform that underpins the smaller Citroën C3 and DS3.', 260, 'petrol', 'Manual', 2020),
('Mitsubishi', 'Lancer', 'Sedan', 'The Mitsubishi Lancer is an automobile nameplate produced by the Japanese manufacturer Mitsubishi Motors since 1973.The Lancer has been marketed as the Colt Lancer, Dodge Colt, Plymouth Colt, Chrysler Valiant Lancer, Chrysler Lancer, Eagle Summit, Hindustan Lancer, Soueast Lioncel, and Mitsubishi Mirage in various countries at different times, and has been sold as the Mitsubishi Galant Fortis in Japan since 2007. It has also been sold as Mitsubishi Lancer Fortis in Taiwan with a different facelift than the Galant Fortis. In Japan, it was sold at a specific retail chain called Car Plaza.', 210, 'petrol', 'Manual', 2017),
('Suzuki', 'Ignis', 'Hatchback', 'The Maruti Ignis has 1 Petrol Engine on offer. The Petrol engine is 1197 cc . It is available with the Manual & Automatic transmission. Depending upon the variant and fuel type the Ignis has a mileage of 20.89 kmpl. The Ignis is a 5 seater and has length of 3700mm, width of 1690mm and a wheelbase of 2435mm.', 70, 'diesel', 'Manual', 2019),
('Kia', 'Cadenza', 'Sedan', 'The Kia Cadenza (also known in South Korea as Kia K7) is a full-size/executive sedan manufactured by Kia. It was launched in 2010 to replace the Kia Opirus/Amanti.', 140, 'petrol', 'Automatic', 2017),
('Infinity', 'Q30', 'Jeep', 'The Infiniti Q30 is a subcompact executive car built and sold by Nissan\'s Infiniti luxury brand from 2016. The Q30 is built on the third-generation Mercedes-Benz A-Class platform to create a small, premium hatchback. The Q30 is a result of the Nissan, Renault and Mercedes partnership agreement to share technology. It ceased production in the UK in mid-2019 as the brand withdrew from Europe altogether at the same time.', 250, 'diesel', 'Automatic', 2019)
('Mercedes-Benz', 'E200', 'Sedan', 'It\'s time for the final showdown, where the winner of last month\'s luxury sedan test goes wheel-to-wheel in a winner-takes all fight against three of the established, premium (and German) stalwarts. That means our Jaguar XF has returned to battle for the British against the Teutonic might of the establishment: the Audi A6, BMW 5 Series and Mercedes-Benz E-Class...', 800, 'diesel', 'Automatic', 2020)
('BMW', '320', 'Sedan', 'The BMW 320 was a car manufactured by Bayerische Motoren Werke AG also known as BMW in Germany from 1937 to 1938, the successor to the 319-based BMW 329. It was offered in 2 door saloon and convertible versions. Approximately 4,200 cars were made, of which 1,835 were cabriolets.', 250, 'petrol', 'Manual', 2015)
('Ford', 'Ranger', 'Truck', 'Ford\s mid-size pickup comes in two body styles with two bed lengths, and its trim levels range from the base model XL to the more luxurious Lariat. All Rangers are powered by a turbocharged 2.3-liter four-cylinder engine and offer a 10-speed automatic transmission; both rear- and four-wheel drive models are available.', 320, 'petrol', 'Automatic', 2019)
('Hyundai', 'Tuscon', 'Hatchback', 'The Hyundai Tucson (Korean: 현대 투싼, romanized: Hyeondae Tussan) (pronounced Tu-són) is a compact crossover SUV (C-segment) produced by the South Korean manufacturer Hyundai since 2004. In the brand\'s lineup, the Tucson fits below the Santa Fe, and above the Kona and Creta. It is named after the city of Tucson, Arizona. The second-generation model has been marketed as the Hyundai ix35 in several markets, including Europe, Australia and China, before reverting back to Tucson for the third-generation.', 140, 'diesel', 'Automatic', 2015)
('Honda', 'Civic', 'Coupe', 'The Honda Civic is a line of cars manufactured by Honda. Originally a subcompact, the Civic has gone through several generational changes, becoming both larger and more upscale, moving into the compact car segment. EPA guidelines for vehicle size class stipulate a car having combined passenger and cargo room of 110 to 119.9 cubic feet (3,110 to 3,400 L) is considered a mid-size car, and as such the tenth generation Civic sedan is technically a small-end mid-size car, although it still competes in the compact class. The Civic coupé is still considered a compact car. ', 240, 'petrol', 'Manual', 2018)
('Fiat', 'Bravo', 'Hatchback', 'The Fiat Bravo (Type 198) is a small family car produced by Italian manufacturer Fiat from 2007 to 2014. It was introduced to the press in January 2007 in Rome, and later to the public in March at the Geneva Motor Show. A minor facelift was available from 2010, with changes to the front grille, door handles and side mirrors, new colors, as well as interior improvements. The car was launched on 21 April 2007.', 80, 'petrol', 'Manual', 2007)
('Dacia', 'Duster', 'Jeep', 'The Dacia Duster is a compact crossover SUV produced and marketed jointly by the French manufacturer Renault and its Romanian subsidiary Dacia since 2010. It is currently in its second generation, launched in the autumn of 2017. It is marketed as the Renault Duster in certain markets such as Latin America, Russia, Ukraine, Asia, the Middle East, and South Africa.', 100, 'diesel', 'Manual', 2018);

