CREATE TABLE CAR(
   CAR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   CAR_BRAND VARCHAR(16) NOT NULL,
   CAR_MODEL VARCHAR(16) NOT NULL,
   CAR_COUPE VARCHAR(16) NOT NULL,
   CAR_DESCRIPTION VARCHAR(1024) NOT NULL,
   CAR_PRICE_PER_DAY DECIMAL NOT NULL,
   CAR_FUEL VARCHAR(16) NOT NULL,
   CAR_TRANSMISSION VARCHAR(16) NOT NULL,
   CAR_YEAR INT NOT NULL,
   CAR_IMAGE VARCHAR(26) NOT NULL,
   CAR_RESERVATIONS VARCHAR(1024)
);

CREATE TABLE RESERVATION(
  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CAR_ID BIGINT,
  USER_NAME VARCHAR(26),
  USER_EMAIL VARCHAR(26),
  USER_NUMBER VARCHAR(26),
  RESERVATION_DATES VARCHAR(1024)
);

CREATE TABLE CONTACT(
    CONTACT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(26),
    USER_EMAIL VARCHAR(26),
    REVIEW_TYPE VARCHAR(26),
    REVIEW VARCHAR(1024)
);

ALTER TABLE RESERVATION ADD FOREIGN KEY(CAR_ID) REFERENCES CAR(CAR_ID);
